[package]
name = "lava"
version = "0.3.0"
build = "build.rs"
authors = ["Anovs <milan.sylvain@gmail.com>"]
description = "Wrapper to manipulate Vulkan more conveniently than with the C API."
license = "MIT"
repository = "https://github.com/Anovs/lava"

[dependencies]