[package]
name = "lava"
version = "0.2.0"
build = "build.rs"
authors = ["Ytawo <milan.sylvain@gmail.com>"]
description = "Vulkan wrapper"
license = "MIT"
repository = "https://github.com/Ytawo/lava"

[dependencies]