[package]
name = "lava"
version = "0.4.6"
build = "build.rs"
authors = ["Anovs <milan.sylvain@gmail.com>"]
description = "Wrapper to manipulate Vulkan more conveniently than with bindings."
license = "MIT"
repository = "https://github.com/Anovs/lava"

[dependencies]
